### ISSUE TITLE
Make migration files so SQL databases can be installed with php muse migration

### ISSUE THREAD

**Issue by jrharless** [qubeshub/com_partners#17]

**Comment by mdlama** [comment]
Hey, Jacob!  Is this in reference to the `install.sql`, or is this referring to putting the Partners component in the admin dropdown?  I was under the impression a migration was only necessary for the latter, and the installation of components was supposed to take care of the former.

**Comment by jrharless** [comment]
Its for the install sqls. The  hubzero guys updated drwho so you no longer
need to run install scripts

**Comment by jrharless** [comment]
If you redownload drwho it has a folder called migrations where this is done

**Comment by mdlama** [comment]
Oh, I see.  Under the idea that migration scripts are for updating the database, it makes sense for migration scripts to take care of the install.sql step.  I'll check it out.

**Comment by jrharless** [comment]
I might need to destroy my vagrant and restart to make sure it works from
the get go, but it a least worked when i deleted drwho and reinstalled it.
