### ISSUE TITLE
Migration scripts fail

### ISSUE THREAD

**Issue by mdlama** [qubeshub/com_partners#25]
Here's what I get:

```
Error: running up() resulted in

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

in Migration20170703150500ComPartners.php
Migration failed! See log messages for details.
```

Any ideas?  Actually, I have a couple questions here:

- Why are there two migration scripts?  They look very similar.
- What is with the up() and down() functions?  The muse command doesn't seem to specify which one you want.

**Comment by jrharless** [comment]
It works if you dont have the database already installed. Ill look into it
and see if i can a drop table to it. Ill be the lab in a bit and can
explain.

**Comment by mdlama** [comment]
I'm gonna grab lunch but then should be back after 1:00.  

Also, re: first bullet point, I should have read the README:  

> The older migration is required fro the component to function properly and installs just the database tables and registers the component with the CMS. The other migration is optional and only installs sample content.

**Comment by mdlama** [comment]
I ran the following and it worked:

```
php muse migration -d=down --file=Migration20170703130200ComPartners.php -f
php muse migration -d=up --file=Migration20170703130200ComPartners.php -f
```

**Comment by jrharless** [comment]
sweet!
